[build]
builder = "NIXPACKS"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["python3", "python3Packages.pip", "gcc"]

[build.nixpacksPlan.phases.install]
cmds = [
  "python -m venv /opt/venv",
  "/opt/venv/bin/pip install -r backend/requirements.txt"
]

[deploy]
startCommand = "cd backend && /opt/venv/bin/gunicorn app:app --bind 0.0.0.0:$PORT"


