
[build]
builder = "NIXPACKS"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["python3", "python3Packages.pip", "gcc"]

[build.nixpacksPlan.phases.install]
cmds = ["pip install -r backend/requirements.txt"]

[deploy]
startCommand = "cd backend && gunicorn app:app --bind 0.0.0.0:$PORT"