/* AUTO-GENERATED by syncKaggle (manual seed). Do not edit manually. */
window.KAGGLE_DATA = {
  "generatedAt": "2026-07-18T13:36:54.748Z",
  "handle": "gastondana",
  "profile": {
    "counts": {
      "competitions": 1,
      "datasets": 26,
      "code": 76,
      "discussion": 35,
      "writeups": 6,
      "benchmarks": 24,
      "followers": 7,
      "following": 2
    },
    "rankings": {
      "datasets": {
        "tier": "Expert",
        "rank": 248,
        "of": 10659,
        "medals": {
          "silver": 1,
          "bronze": 2
        }
      },
      "notebooks": {
        "tier": "Expert",
        "rank": 415,
        "of": 62018,
        "highestEver": 412,
        "medals": {
          "bronze": 18
        }
      }
    }
  },
  "notebooks": [
    {
      "title": "Heart-Disease-Recirculation-Loop(AUC 0.964)",
      "url": "https://www.kaggle.com/code/gastondana/heart-disease-recirculation-loop-auc-0-964",
      "votes": 41,
      "score": "0.95379",
      "comments": 2,
      "updated": "5 months ago"
    },
    {
      "title": "ARC-AGI-2-Starter",
      "url": "https://www.kaggle.com/code/gastondana/arc-agi-2-starter",
      "votes": 21,
      "score": null,
      "comments": 0,
      "updated": "3 months ago"
    },
    {
      "title": "SANS Multi-Modal Integration Challenge",
      "url": "https://www.kaggle.com/code/gastondana/sans-multi-modal-integration-challenge",
      "votes": 18,
      "score": null,
      "comments": 3,
      "updated": "5 months ago"
    },
    {
      "title": "Spectral Soul: Head-to-Head Analysis-Lyria vs Suno",
      "url": "https://www.kaggle.com/code/gastondana/spectral-soul-head-to-head-analysis-lyria-vs-suno",
      "votes": 16,
      "score": null,
      "comments": 4,
      "updated": "3 months ago"
    },
    {
      "title": "NB04: Visual Intelligence - Gravity's Series v1",
      "url": "https://www.kaggle.com/code/gastondana/nb04-visual-intelligence-gravity-s-series-v1",
      "votes": 14,
      "score": null,
      "comments": 0,
      "updated": "4 months ago"
    },
    {
      "title": "KING_HUD-Sentinel_Manual",
      "url": "https://www.kaggle.com/code/gastondana/king-hud-sentinel-manual",
      "votes": 11,
      "score": null,
      "comments": 0,
      "updated": "5 months ago"
    },
    {
      "title": "Gender Violence in Spain",
      "url": "https://www.kaggle.com/code/gastondana/gender-violence-in-spain",
      "votes": 11,
      "score": null,
      "comments": 4,
      "updated": "3 months ago"
    },
    {
      "title": "HCB_LIFECYCLE_0001_PRECISION",
      "url": "https://www.kaggle.com/code/gastondana/hcb-lifecycle-0001-precision",
      "votes": 10,
      "score": null,
      "comments": 0,
      "updated": "2 months ago"
    },
    {
      "title": "KING-HUD_Human-vs-Agentic-Remediation-Study",
      "url": "https://www.kaggle.com/code/gastondana/king-hud-human-vs-agentic-remediation-study",
      "votes": 9,
      "score": null,
      "comments": 0,
      "updated": "5 months ago"
    },
    {
      "title": "Car price Prediction",
      "url": "https://www.kaggle.com/code/gastondana/car-price-prediction",
      "votes": 9,
      "score": null,
      "comments": 0,
      "updated": "3 months ago"
    },
    {
      "title": "gasman-march-mania-2026-rnd-v1",
      "url": "https://www.kaggle.com/code/gastondana/march-mania-2026",
      "votes": 9,
      "score": null,
      "comments": 0,
      "updated": "4 months ago"
    },
    {
      "title": "LogiCore Ultra: Comprehensive Results & Efficiency",
      "url": "https://www.kaggle.com/code/gastondana/logicore-ultra-comprehensive-results-efficiency",
      "votes": 9,
      "score": null,
      "comments": 0,
      "updated": "2 months ago"
    },
    {
      "title": "Battleship_PvP_GasMan_Operations_Dock_BSG",
      "url": "https://www.kaggle.com/code/gastondana/battleship-pvp-gasman-operations-dock-bsg",
      "votes": 7,
      "score": null,
      "comments": 0,
      "updated": "5 months ago"
    },
    {
      "title": "I'm afraid Not, Mr. Darcy. Identify authors",
      "url": "https://www.kaggle.com/code/gastondana/i-m-afraid-not-mr-darcy-identify-authors",
      "votes": 7,
      "score": null,
      "comments": 3,
      "updated": "2 months ago"
    },
    {
      "title": "GasMan Creative Output Summary - Last 2 Months",
      "url": "https://www.kaggle.com/code/gastondana/gasman-creative-output-summary-last-2-months",
      "votes": 7,
      "score": null,
      "comments": 0,
      "updated": "10 days ago"
    },
    {
      "title": "The Rook-Mate Challenge: Conversion IQ",
      "url": "https://www.kaggle.com/code/gastondana/the-rook-mate-challenge-conversion-iq",
      "votes": 7,
      "score": null,
      "comments": 0,
      "updated": "5 months ago"
    },
    {
      "title": "The Kinetic Arbitrator: Physics vs. Narrative",
      "url": "https://www.kaggle.com/code/gastondana/the-kinetic-arbitrator-physics-vs-narrative",
      "votes": 6,
      "score": null,
      "comments": 0,
      "updated": "5 months ago"
    },
    {
      "title": "Industrial Kinetic Logic - Fatigue Baseline",
      "url": "https://www.kaggle.com/code/gastondana/industrial-kinetic-logic-fatigue-baseline",
      "votes": 6,
      "score": null,
      "comments": 0,
      "updated": "6 months ago"
    },
    {
      "title": "KING-HUD Shift 2: Zombie Signatures & Agentic Hand",
      "url": "https://www.kaggle.com/code/gastondana/king-hud-shift-2-zombie-signatures-agentic-hand",
      "votes": 6,
      "score": null,
      "comments": 0,
      "updated": "5 months ago"
    },
    {
      "title": "OSD-366 Visual Companion-53BP1 Foci & Mouse Strain",
      "url": "https://www.kaggle.com/code/gastondana/osd-366-visual-companion-53bp1-foci-mouse-strain",
      "votes": 6,
      "score": null,
      "comments": 0,
      "updated": "3 days ago"
    }
  ],
  "datasets": [
    {
      "title": "Human Creativity Benchmark(HCB) - Community",
      "url": "https://www.kaggle.com/datasets/gastondana/human-creativity-benchmarkhcb-community",
      "votes": 27,
      "usability": 9.4,
      "size": "1 kB",
      "medal": "silver",
      "updated": "3 months ago"
    },
    {
      "title": "SPACEDOS",
      "url": "https://www.kaggle.com/datasets/gastondana/spacedos",
      "votes": 10,
      "usability": 9.4,
      "size": "13 MB",
      "medal": "bronze",
      "updated": "5 months ago"
    },
    {
      "title": "Solar-Icicles-Multimodal-V1",
      "url": "https://www.kaggle.com/datasets/gastondana/solar-icicles-multimodal-v1",
      "votes": 8,
      "usability": 10,
      "size": "71 MB",
      "medal": "bronze",
      "updated": "3 months ago"
    },
    {
      "title": "AI Public Opinion 2024-2026 (Core Toplines)",
      "url": "https://www.kaggle.com/datasets/gastondana/ai-public-opinion-2024-2026-core-csv",
      "votes": 5,
      "usability": 9.4,
      "size": "975 B",
      "medal": "bronze",
      "updated": "4 months ago"
    },
    {
      "title": "OSD-120 CARA Arabidopsis ISS RNA-Seq rRNArm",
      "url": "https://www.kaggle.com/datasets/gastondana/osd-120-cara-arabidopsis-iss-rna-seq-rrnarm",
      "votes": 5,
      "usability": 8.2,
      "size": "83 MB",
      "medal": null,
      "updated": "4 months ago"
    },
    {
      "title": "US-Cardiovascular-Mortality-Trends-CDC",
      "url": "https://www.kaggle.com/datasets/gastondana/us-cardiovascular-mortality-trends-cdc",
      "votes": 4,
      "usability": 8.8,
      "size": "3 MB",
      "medal": null,
      "updated": "5 months ago"
    },
    {
      "title": "Never-Forget-The-Basket: Multi-Arc Generation",
      "url": "https://www.kaggle.com/datasets/gastondana/never-forget-the-basket",
      "votes": 4,
      "usability": 8.8,
      "size": "35 MB",
      "medal": null,
      "updated": "4 months ago"
    },
    {
      "title": "PencilPhysics-V1",
      "url": "https://www.kaggle.com/datasets/gastondana/pencilphysics-v1",
      "votes": 4,
      "usability": 9.4,
      "size": "71 MB",
      "medal": null,
      "updated": "2 months ago"
    },
    {
      "title": "Pencil Physics-SOTA Multimodal Reasoning Telemetry",
      "url": "https://www.kaggle.com/datasets/gastondana/pencil-physics-sota-multimodal-reasoning-telemetry",
      "votes": 3,
      "usability": 10,
      "size": "1 kB",
      "medal": null,
      "updated": "2 months ago"
    },
    {
      "title": "KING-HUD Shift 1: Baseline Decay & Scout Telemetry",
      "url": "https://www.kaggle.com/datasets/gastondana/king-hud-shift-1-baseline-decay-and-scout-telemetry",
      "votes": 3,
      "usability": 9.4,
      "size": "2 kB",
      "medal": null,
      "updated": "5 months ago"
    },
    {
      "title": "LogiCore Ultra: Surgical & Efficient Results",
      "url": "https://www.kaggle.com/datasets/gastondana/logicore-ultra-surgical-and-efficient-results",
      "votes": 3,
      "usability": 9.4,
      "size": "2 kB",
      "medal": null,
      "updated": "2 months ago"
    },
    {
      "title": "KING-HUD Shift 2: Redline & Zombie Kernel Analysis",
      "url": "https://www.kaggle.com/datasets/gastondana/king-hud-shift-2-redline-and-zombie-kernel-analysis",
      "votes": 3,
      "usability": 9.4,
      "size": "2 kB",
      "medal": null,
      "updated": "5 months ago"
    },
    {
      "title": "Geospatial Data for Anomaly Detection in Xingu",
      "url": "https://www.kaggle.com/datasets/gastondana/geospatial-data-for-anomaly-detection-in-xingu",
      "votes": 3,
      "usability": 3.1,
      "size": "101 MB",
      "medal": null,
      "updated": "a year ago"
    },
    {
      "title": "Cognitive SRE-Shift 2 vs Shift 3 Handover Data",
      "url": "https://www.kaggle.com/datasets/gastondana/cognitive-sre-shift-2-vs-shift-3-handover-data",
      "votes": 3,
      "usability": 2.9,
      "size": "1 kB",
      "medal": null,
      "updated": "5 months ago"
    },
    {
      "title": "OSD-679: SANS Multi-Modal Space Biology Benchmark",
      "url": "https://www.kaggle.com/datasets/gastondana/osd-679-sans-multi-modal-space-biology-benchmark",
      "votes": 3,
      "usability": 9.4,
      "size": "33 kB",
      "medal": null,
      "updated": "5 months ago"
    },
    {
      "title": "Flow Props POV Benchmark 03-2026",
      "url": "https://www.kaggle.com/datasets/gastondana/flow-props-pov-benchmark-032026",
      "votes": 3,
      "usability": 2.5,
      "size": "71 MB",
      "medal": null,
      "updated": "4 months ago"
    },
    {
      "title": "Industrial Kinetic Reasoning & Metabolic Flux",
      "url": "https://www.kaggle.com/datasets/gastondana/industrial-kinetic-reasoning-and-metabolic-flux",
      "votes": 3,
      "usability": 3.1,
      "size": "821 B",
      "medal": null,
      "updated": "6 months ago"
    },
    {
      "title": "a-game-02-whistleblower",
      "url": "https://www.kaggle.com/datasets/gastondana/a-game-02-whistleblower",
      "votes": 3,
      "usability": 7.5,
      "size": "4 MB",
      "medal": null,
      "updated": "5 months ago"
    },
    {
      "title": "Parcel Peak 2025: Biometric Performance Audit",
      "url": "https://www.kaggle.com/datasets/gastondana/ups-peak-2025-biometric-performance-audit",
      "votes": 3,
      "usability": 8.8,
      "size": "830 B",
      "medal": null,
      "updated": "6 months ago"
    },
    {
      "title": "S2_And_STRM",
      "url": "https://www.kaggle.com/datasets/gastondana/s2-and-strm",
      "votes": 2,
      "usability": 3.1,
      "size": "1 GB",
      "medal": null,
      "updated": "a year ago"
    }
  ],
  "benchmarks": [
    {
      "title": "Strategic Endgame Logic: KRvK Conversion",
      "url": "https://www.kaggle.com/benchmarks/gastondana/strategic-endgame-logic-krvk-conversion",
      "type": "Community Benchmark",
      "updated": "5 months ago",
      "version": "V1",
      "votes": 1,
      "description": "A \"Logic Gauntlet\" for LLMs. This benchmark tests the transition from chess theory to action in King+Rook vs King endgames. Models must convert a win without the \"Rook Incident\", blundering the winning piece. Measures Strategic IQ vs. rule-following."
    },
    {
      "title": "Industrial Kinetic Reasoning & Metabolic Flux",
      "url": "https://www.kaggle.com/benchmarks/gastondana/industrial-kinetic-reasoning-and-metabolic-flux",
      "type": "Community Benchmark",
      "updated": "6 months ago",
      "version": "V1",
      "votes": 1,
      "description": "Evaluating VLM & Large World Model (LWM) reasoning in industrial environments. This benchmark tests model accuracy in correlating 72-hour metabolic flux telemetry with visual human-system interactions (HSI) within high-density logistics."
    },
    {
      "title": "SANS_Granular_Forensic_Audit_v5_1",
      "url": "https://www.kaggle.com/benchmarks/tasks/gastondana/sans-multi-modal-integration",
      "type": "Task",
      "updated": "5 months ago",
      "version": "V8",
      "votes": 1,
      "description": ""
    },
    {
      "title": "Spectral Soul: Generative Audio Benchmark",
      "url": "https://www.kaggle.com/benchmarks/gastondana/spectral-soul-generative-audio-standard",
      "type": "Community Benchmark",
      "updated": "3 months ago",
      "version": "V1",
      "votes": 0,
      "description": "SS: Audio v1. 40% Rhythm (95BPM) / 60% Purity (1500x). Signal telemetry for where math meets the groove. Open-source standard."
    },
    {
      "title": "Syn_Tax: The 3D Spatial Intelligence Gauntlet",
      "url": "https://www.kaggle.com/benchmarks/gastondana/syn-tax-the-3d-spatial-intelligence-gauntlet",
      "type": "Community Benchmark",
      "updated": "3 months ago",
      "version": "V1",
      "votes": 0,
      "description": "Hard-gate testing for manifold integrity and yapping-tax efficiency."
    },
    {
      "title": "LogiCore Ultra",
      "url": "https://www.kaggle.com/benchmarks/gastondana/logicore-ultra",
      "type": "Community Benchmark",
      "updated": "2 months ago",
      "version": "V1",
      "votes": 0,
      "description": "Initial phase of a high-granularity logic evaluation. Currently utilizing a strict pass/fail binary to establish a baseline for reasoning consistency, with a planned migration to a 0.0001 precision scoring format to capture subtle model variances."
    },
    {
      "title": "Pencil Physics: Mechanical Logic Benchmark",
      "url": "https://www.kaggle.com/benchmarks/gastondana/pencil-physics-mechanical-logic-benchmark",
      "type": "Community Benchmark",
      "updated": "20 days ago",
      "version": "V1",
      "votes": 0,
      "description": "A rigorous multimodal benchmark evaluating state-of-the-art AI on strict spatial reasoning, structural integrity, and physical constraint adherence."
    },
    {
      "title": "OSD-120 Resilience Evaluation",
      "url": "https://www.kaggle.com/benchmarks/gastondana/osd-120-resilience-evaluation",
      "type": "Community Benchmark",
      "updated": "4 days ago",
      "version": "V1",
      "votes": 0,
      "description": "Benchmark evaluating LLMs on OSD-120 Arabidopsis RNA-seq. Models must autonomously clean data, perform GLM interaction modeling, and retrieve 35 canonical genes. Tests pipeline resilience and statistical fidelity in space-biology."
    },
    {
      "title": "HCB_LIFECYCLE_0001",
      "url": "https://www.kaggle.com/benchmarks/tasks/gastondana/hcb-lifecycle-0001",
      "type": "Task",
      "updated": "2 months ago",
      "version": "V8",
      "votes": 0,
      "description": "v8: 1,000-Pt Numerical Precision (The Metric Gate)"
    },
    {
      "title": "LEP-95: G-Funk Rhythmic Stability",
      "url": "https://www.kaggle.com/benchmarks/tasks/gastondana/lep-95-g-funk-rhythmic-stability",
      "type": "Task",
      "updated": "3 months ago",
      "version": "V3",
      "votes": 0,
      "description": "v2.1 Milli-Score Audit: 21-point Dynamic Radar (0-1000 Scale)."
    },
    {
      "title": "HCB_LIFECYCLE_01",
      "url": "https://www.kaggle.com/benchmarks/tasks/gastondana/hcb-lifecycle-01",
      "type": "Task",
      "updated": "3 months ago",
      "version": "V1",
      "votes": 0,
      "description": "Professional Handbag Lifecycle: Ideation to Refinement."
    },
    {
      "title": "forensic_court_arbitration",
      "url": "https://www.kaggle.com/benchmarks/tasks/gastondana/forensic-court-arbitration",
      "type": "Task",
      "updated": "5 months ago",
      "version": "V3",
      "votes": 0,
      "description": "Multi-Phase Audit: Phase 1 (Physics vs Narrative) & Phase 2 (Whistleblower Dilemma)."
    },
    {
      "title": "Syn_Tax_Orchestration_Gauntlet",
      "url": "https://www.kaggle.com/benchmarks/tasks/gastondana/syn-tax-orchestration-gauntlet",
      "type": "Task",
      "updated": "3 months ago",
      "version": "V1",
      "votes": 0,
      "description": ""
    },
    {
      "title": "Syn_Tax_Foundational_Spatial_Logic",
      "url": "https://www.kaggle.com/benchmarks/tasks/gastondana/syn-tax-foundational-spatial-logic",
      "type": "Task",
      "updated": "3 months ago",
      "version": "V1",
      "votes": 0,
      "description": ""
    },
    {
      "title": "Syn_Tax_Blueprint_Fidelity_v2_5",
      "url": "https://www.kaggle.com/benchmarks/tasks/gastondana/syn-tax-blueprint-fidelity-v2-5",
      "type": "Task",
      "updated": "3 months ago",
      "version": "V1",
      "votes": 0,
      "description": ""
    },
    {
      "title": "Syn_Tax_v4_5_Industrial_Audit",
      "url": "https://www.kaggle.com/benchmarks/tasks/gastondana/syn-tax-v4-5-industrial-audit",
      "type": "Task",
      "updated": "3 months ago",
      "version": "V1",
      "votes": 0,
      "description": ""
    },
    {
      "title": "kinetic_numeric_inference_med",
      "url": "https://www.kaggle.com/benchmarks/tasks/gastondana/industrial-fatigue-audit",
      "type": "Task",
      "updated": "6 months ago",
      "version": "V2",
      "votes": 0,
      "description": "MEDIUM: Zero-context fatigue detection. Models must infer risk from raw numerical telemetry ONLY (No text hints)."
    },
    {
      "title": "Pencil Physics: Mechanical Constraint Test",
      "url": "https://www.kaggle.com/benchmarks/tasks/gastondana/pencil-physics-mechanical-constraint-test",
      "type": "Task",
      "updated": "2 months ago",
      "version": "V2",
      "votes": 0,
      "description": "Scores 100 questions on mechanical constraints. Result is % of correct identifications."
    },
    {
      "title": "osd120_resilience_spec_json",
      "url": "https://www.kaggle.com/benchmarks/tasks/gastondana/osd120-resilience-spec-json",
      "type": "Task",
      "updated": "4 days ago",
      "version": "V1",
      "votes": 0,
      "description": "Can the model design a GLM-style OSD-120 resilience plan in JSON?"
    },
    {
      "title": "bexar-next-event-prediction",
      "url": "https://www.kaggle.com/benchmarks/tasks/gastondana/bexar-next-event-prediction",
      "type": "Task",
      "updated": "2 days ago",
      "version": "V2",
      "votes": 0,
      "description": "Predict the date of the next Bexar County tornado after 2025, given all historical events through 2025."
    }
  ]
};
